# Generated by Django 3.2.7 on 2021-09-16 04:57

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=64)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricketapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricketapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('age', models.PositiveIntegerField(default=25)),
                ('total_runs', models.PositiveIntegerField(default=0)),
                ('total_wickets', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, to='cricketapp.country')),
                ('team', models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, to='cricketapp.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('loser', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loser', to='cricketapp.team')),
                ('player', smart_selects.db_fields.GroupedForeignKey(group_field='name', on_delete=django.db.models.deletion.CASCADE, to='cricketapp.team')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner', to='cricketapp.team')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
