# Generated by Django 3.2.7 on 2021-09-16 04:58

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='team', on_delete=django.db.models.deletion.CASCADE, to='cricketapp.player'),
        ),
    ]
