# Generated by Django 3.2.7 on 2021-09-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0002_alter_match_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='player',
            new_name='player_of_match',
        ),
    ]
