# Generated by Django 3.2.7 on 2021-09-16 05:05

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0003_rename_player_match_player_of_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bowler_of_match',
            field=smart_selects.db_fields.GroupedForeignKey(default=1, group_field='team', on_delete=django.db.models.deletion.CASCADE, related_name='bowler', to='cricketapp.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_of_match',
            field=smart_selects.db_fields.GroupedForeignKey(default=1, group_field='team', on_delete=django.db.models.deletion.CASCADE, related_name='player', to='cricketapp.player'),
        ),
    ]
