# Generated by Django 3.2.7 on 2021-09-16 05:07

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0004_auto_20210916_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='fielder_of_match',
            field=smart_selects.db_fields.GroupedForeignKey(default=1, group_field='team', on_delete=django.db.models.deletion.CASCADE, related_name='fielder', to='cricketapp.player'),
        ),
    ]
