# Generated by Django 3.2.7 on 2021-09-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0005_match_fielder_of_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='loser_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='match',
            name='loser_wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_wickets',
            field=models.IntegerField(default=0),
        ),
    ]
