# Generated by Django 3.2.7 on 2021-09-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0006_auto_20210916_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=2),
        ),
    ]
